<?php

namespace App\Controller;

use App\Entity\Admin;
use App\Entity\Customer;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;

#[Route('/api', name: 'api_')]
class AuthController extends AbstractController
{
    public function __construct(
        private EntityManagerInterface $em,
        private UserPasswordHasherInterface $passwordHasher,
        private JWTTokenManagerInterface $jwtManager
    ) {
    }

    #[Route('/register', name: 'register', methods: ['POST'])]
    public function register(Request $request): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if (!isset($data['email']) || !isset($data['password']) || !isset($data['name'])) {
            return new JsonResponse(['error' => 'Email, password, and name are required'], Response::HTTP_BAD_REQUEST);
        }

        // Check if user already exists
        $existingUser = $this->em->getRepository(User::class)->findOneBy(['email' => $data['email']]);
        if ($existingUser) {
            return new JsonResponse(['error' => 'User with this email already exists'], Response::HTTP_CONFLICT);
        }

        $customer = new Customer();
        $customer->setEmail($data['email']);
        $customer->setName($data['name']);
        $customer->setPhone($data['phone'] ?? null);
        // Password is hashed automatically by Symfony's UserPasswordHasherInterface
        $customer->setPassword($this->passwordHasher->hashPassword($customer, $data['password']));

        $this->em->persist($customer);
        $this->em->flush();

        return new JsonResponse([
            'message' => 'Customer registered successfully',
            'user' => [
                'id' => $customer->getId(),
                'email' => $customer->getEmail(),
                'name' => $customer->getName(),
                'roles' => $customer->getRoles(),
            ]
        ], Response::HTTP_CREATED);
    }

    #[Route('/register/admin', name: 'register_admin', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function registerAdmin(Request $request): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        if (!isset($data['email']) || !isset($data['password']) || !isset($data['name'])) {
            return new JsonResponse(['error' => 'Email, password, and name are required'], Response::HTTP_BAD_REQUEST);
        }

        // Check if user already exists
        $existingUser = $this->em->getRepository(User::class)->findOneBy(['email' => $data['email']]);
        if ($existingUser) {
            return new JsonResponse(['error' => 'User with this email already exists'], Response::HTTP_CONFLICT);
        }

        $admin = new Admin();
        $admin->setEmail($data['email']);
        $admin->setName($data['name']);
        $admin->setPhone($data['phone'] ?? null);
        // Password is hashed automatically by Symfony's UserPasswordHasherInterface
        $admin->setPassword($this->passwordHasher->hashPassword($admin, $data['password']));

        $this->em->persist($admin);
        $this->em->flush();

        return new JsonResponse([
            'message' => 'Admin registered successfully',
            'user' => [
                'id' => $admin->getId(),
                'email' => $admin->getEmail(),
                'name' => $admin->getName(),
                'roles' => $admin->getRoles(),
            ]
        ], Response::HTTP_CREATED);
    }

    #[Route('/login', name: 'login', methods: ['POST'])]
    public function login(): JsonResponse
    {
        // This route is handled by json_login in security.yaml
        // JWT token is automatically generated by LexikJWTBundle
        // This method should not be reached, but if it is, return an error
        return new JsonResponse(['error' => 'Login endpoint is handled automatically by JWT'], Response::HTTP_METHOD_NOT_ALLOWED);
    }

    #[Route('/admin/users', name: 'admin_users_list', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function listAllUsers(): JsonResponse
    {
        $users = $this->em->getRepository(User::class)->findAll();

        $usersData = array_map(function (User $user) {
            return [
                'id' => $user->getId(),
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'phone' => $user->getPhone(),
                'role' => in_array('ROLE_ADMIN', $user->getRoles()) ? 'ROLE_ADMIN' : 'ROLE_CUSTOMER',
                'roles' => $user->getRoles(),
                'createdAt' => $user->getCreatedAt() ? $user->getCreatedAt()->format('c') : null,
            ];
        }, $users);

        return new JsonResponse([
            'users' => $usersData,
            'total' => count($usersData)
        ], Response::HTTP_OK);
    }

    #[Route('/admin/users', name: 'admin_users_create', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function createUser(Request $request): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        $type = strtolower(trim((string)($data['type'] ?? 'customer')));
        $name = trim((string)($data['name'] ?? ''));
        $email = trim((string)($data['email'] ?? ''));
        $password = (string)($data['password'] ?? '');
        $phone = isset($data['phone']) ? trim((string)$data['phone']) : null;

        if ($name === '' || $email === '' || $password === '') {
            return new JsonResponse(['error' => 'Name, email and password are required'], Response::HTTP_BAD_REQUEST);
        }
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return new JsonResponse(['error' => 'Invalid email'], Response::HTTP_BAD_REQUEST);
        }
        if (strlen($password) < 6) {
            return new JsonResponse(['error' => 'Password must be at least 6 characters'], Response::HTTP_BAD_REQUEST);
        }

        $existingUser = $this->em->getRepository(User::class)->findOneBy(['email' => $email]);
        if ($existingUser) {
            return new JsonResponse(['error' => 'User with this email already exists'], Response::HTTP_CONFLICT);
        }

        $user = $type === 'admin' ? new Admin() : new Customer();
        $user->setName($name);
        $user->setEmail($email);
        $user->setPhone($phone ?: null);
        $user->setPassword($this->passwordHasher->hashPassword($user, $password));

        $this->em->persist($user);
        $this->em->flush();

        return new JsonResponse([
            'message' => 'User created',
            'user' => [
                'id' => $user->getId(),
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'phone' => $user->getPhone(),
                'roles' => $user->getRoles(),
                'createdAt' => $user->getCreatedAt() ? $user->getCreatedAt()->format('c') : null,
            ]
        ], Response::HTTP_CREATED);
    }

    #[Route('/admin/users/{id}', name: 'admin_users_get', methods: ['GET'])]
    #[IsGranted('ROLE_ADMIN')]
    public function getUserById(int $id): JsonResponse
    {
        $user = $this->em->getRepository(User::class)->find($id);
        if (!$user) {
            return new JsonResponse(['error' => 'User not found'], Response::HTTP_NOT_FOUND);
        }

        return new JsonResponse([
            'id' => $user->getId(),
            'name' => $user->getName(),
            'email' => $user->getEmail(),
            'phone' => $user->getPhone(),
            'roles' => $user->getRoles(),
            'createdAt' => $user->getCreatedAt() ? $user->getCreatedAt()->format('c') : null,
            'type' => $user instanceof Admin ? 'admin' : 'customer',
        ], Response::HTTP_OK);
    }

    #[Route('/admin/users/{id}', name: 'admin_users_update', methods: ['PUT', 'PATCH'])]
    #[IsGranted('ROLE_ADMIN')]
    public function updateUser(int $id, Request $request): JsonResponse
    {
        $user = $this->em->getRepository(User::class)->find($id);
        if (!$user) {
            return new JsonResponse(['error' => 'User not found'], Response::HTTP_NOT_FOUND);
        }

        $data = json_decode($request->getContent(), true);

        if (isset($data['name'])) {
            $name = trim((string)$data['name']);
            if ($name === '') {
                return new JsonResponse(['error' => 'Name cannot be empty'], Response::HTTP_BAD_REQUEST);
            }
            $user->setName($name);
        }

        if (isset($data['email'])) {
            $email = trim((string)$data['email']);
            if ($email === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
                return new JsonResponse(['error' => 'Invalid email'], Response::HTTP_BAD_REQUEST);
            }
            $existingUser = $this->em->getRepository(User::class)->findOneBy(['email' => $email]);
            if ($existingUser && $existingUser->getId() !== $user->getId()) {
                return new JsonResponse(['error' => 'Email already in use'], Response::HTTP_CONFLICT);
            }
            $user->setEmail($email);
        }

        if (array_key_exists('phone', $data)) {
            $phone = $data['phone'];
            $user->setPhone($phone ? trim((string)$phone) : null);
        }

        if (!empty($data['password'])) {
            $password = (string)$data['password'];
            if (strlen($password) < 6) {
                return new JsonResponse(['error' => 'Password must be at least 6 characters'], Response::HTTP_BAD_REQUEST);
            }
            $user->setPassword($this->passwordHasher->hashPassword($user, $password));
        }

        $this->em->flush();

        return new JsonResponse([
            'message' => 'User updated',
            'user' => [
                'id' => $user->getId(),
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'phone' => $user->getPhone(),
                'roles' => $user->getRoles(),
                'createdAt' => $user->getCreatedAt() ? $user->getCreatedAt()->format('c') : null,
            ]
        ], Response::HTTP_OK);
    }

    #[Route('/admin/users/{id}', name: 'admin_users_delete', methods: ['DELETE'])]
    #[IsGranted('ROLE_ADMIN')]
    public function deleteUser(int $id): JsonResponse
    {
        $user = $this->em->getRepository(User::class)->find($id);
        if (!$user) {
            return new JsonResponse(['error' => 'User not found'], Response::HTTP_NOT_FOUND);
        }

        $current = $this->getUser();
        if ($current instanceof User && $current->getId() === $user->getId()) {
            return new JsonResponse(['error' => 'You cannot delete your own account'], Response::HTTP_BAD_REQUEST);
        }

        if ($user instanceof Admin) {
            $adminCount = (int)$this->em->createQuery('SELECT COUNT(a.id) FROM App\Entity\Admin a')->getSingleScalarResult();
            if ($adminCount <= 1) {
                return new JsonResponse(['error' => 'Cannot delete the last admin'], Response::HTTP_BAD_REQUEST);
            }
        }

        $this->em->remove($user);
        $this->em->flush();

        return new JsonResponse(['message' => 'User deleted'], Response::HTTP_OK);
    }
}
